name: Release Docs

on:
  push:
    branches:
      main

jobs:
  build:
    name: Build Docs 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: "Docs"
          doxyfile-path: "Doxyfile" 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: public/docs
          folder: Docs/html
